use_frameworks!

platform :ios, '9.0'

target 'BSHHousekeeperLog_Example' do
  pod 'BSHHousekeeperLog', :path => '../'

  target 'BSHHousekeeperLog_Tests' do
    inherit! :search_paths

    
  end
end
